### ISSUE TITLE
Key combi Shift+8 or AltGr+8 not working

### ISSUE THREAD

**Issue by deathaxe** [randy3k/Console#2]
First of all: Thanks for your efforts. Really cool to see this plugin.

Played around with it a little bit. Works very well already. Even Midnight Commander via bash (WSL) works. Funny to see MC in ST :-)

As the title says I found some key bindings, which do not work.

<kbd>Shift+8</kbd> is used for `(` on german keyboard layout and <kbd>AltGr+8</kbd> is used for `[`.

Same with <kbd>Shift+´</kbd>  

<kbd>AltGr+e</kbd> should type `€`.

**Comment by randy3k** [comment]
Ai...I don’t have any experience with other keyboard layouts. It will be great if you could try fixing it. I am sure you have had difficulties with other plugins.

**Comment by deathaxe** [comment]
Found the culprit after a short research. Its not even your plugin. All the issues are caused by user defined key bindings which intend to fix a couple of auto-pairing issues. They just override the `conslole_keypress` command. After adding the context 

```
	{ "key": "setting.console_view", "operator": "equal", "operand": false },
```

to each of them, everything works fine. Sorry for bothering.
