### ISSUE TITLE
ctrl+delete, ctrl+backspace not working.

### ISSUE THREAD

**Issue by bantya** [randy3k/Console#3]
First of all, I got to know about this package on Sublime Text forum. I honestly have to tell you that this is a very useful package.

Everything is beyond expectations here, but there are some quirks (I am on **Windows 10**):

1. Hitting <kbd>Ctrl+Delete</kbd> and <kbd>Ctrl+BackSpace</kbd> does erase the whole word on right and left of cursor respectively, this does not work here. (Hitting plain Delete and BackSpace works though.)

2. I generated my own custom theme, but can't activate it now.

3. The ANSI color sequences does not show up out-of-the-box. I have to manually activate the utility I use called [Ansicon](https://github.com/adoxa/ansicon) to display them correctly. (I have `256colors` setting turned on).

4. Cannot use copy-paste from the Console view.

Anyways, I must tell you that this is a great plugin 😊.

**Comment by randy3k** [comment]
1. I will look into it.

2. Did you select the "user" theme?

3. Why you need ANSICON? It is working fine on my machine.
<img width="623" alt="screen shot 2018-06-20 at 1 39 45 pm" src="https://user-images.githubusercontent.com/1690993/41674988-6cb8b118-748f-11e8-99ba-0f43b7d56b55.png">

4. Ctrl-C and Ctrl-V are special sequence, you need to use `Ctrl+Shift+C` or `Ctrl+Shift+V` for now.

   This behavior can be improved by checking if there is a selection. If there is a selection, trigger copy and paste; if there is no selection, trigger the regular sequences.

**Comment by randy3k** [comment]
I still cannot make `ctrl-backspace` to make on `cmd.exe`. It seems that `cmd.exe` doesn't understand the regular `ctrl-backspace` stroke `\x1b\x7f`. It works in `bash.exe` though.

**Comment by bantya** [comment]
Thanks for the quick reply. The <kbd>ctrl+backspace</kbd> and <kbd>ctrl+delete</kbd> keys now work just fine, Copy also works fine but still no luck for pasting. I double checked everything with `nature_terminal` on and off but nothing!

**Comment by randy3k** [comment]
May you have overridden the `ctrl+v` paste command? Check https://forum.sublimetext.com/t/finally-a-multi-platform-terminal-running-in-sublime-text/37560/58?u=randy3k

**Comment by bantya** [comment]
Thanks @randy3k, https://forum.sublimetext.com/t/finally-a-multi-platform-terminal-running-in-sublime-text/37560/59?u=bantya solved my problem.

**Comment by rzdys** [comment]
> I am using 7.58.3 and the `ctrl` + `backspace` is not working. I am using Ubuntu 22.04 fresh install in which the gnome terminal does not support `ctrl` + `backspace` as well, however `ctrl` + `delete` is working as expected.
> 
> --- update `alt` + `backspace` is working.

As a workaround, I added this in key bindings ` { "keys": ["ctrl+backspace"], "command": "terminus_keypress", "args": {"key": "backspace", "alt": true}, "context": [{"key": "terminus_view"}] }`
