### ISSUE TITLE
Console is completely black with blinking cursor

### ISSUE THREAD

**Issue by poroale** [randy3k/Console#4]
After installing the package I get the following messages in Sublime's console:
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 1066, in run_
>     return self.run(edit, **args)
>   File "/home/aap/.config/sublime-text-3/Packages/Console/console.py", line 826, in run
>     console.open(**kwargs)
>   File "/home/aap/.config/sublime-text-3/Packages/Console/console.py", line 390, in open
>     self.process = ConsolePtyProcess.spawn(cmd, cwd=cwd, env=_env, dimensions=size)
>   File "/home/aap/.config/sublime-text-3/Packages/ptyprocess/all/ptyprocess/ptyprocess.py", line 256, in spawn
>     max_fd = resource.getrlimit(resource.RLIMIT_NOFILE)[0]
>   File "/home/aap/.config/sublime-text-3/Packages/ptyprocess/all/ptyprocess/resource.py", line 9, in getrlimit
>     soft_limit = int(subprocess.check_output(['ulimit', '-Sn']))
>   File "./python3.3/subprocess.py", line 576, in check_output
>   File "./python3.3/subprocess.py", line 819, in __init__
>   File "./python3.3/subprocess.py", line 1448, in _execute_child
> FileNotFoundError: [Errno 2] No such file or directory: 'ulimit'
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 1066, in run_
>     return self.run(edit, **args)
>   File "/home/aap/.config/sublime-text-3/Packages/Console/console.py", line 476, in run
>     screen = console.screen
> AttributeError: 'Console' object has no attribute 'screen'

The terminal is black with a blinking cursor, and it does not seem to be responsive.

I'm running Ubuntu 18.04 LTS.

**Comment by randy3k** [comment]
It seems that your ubuntu doesn't come with `ulimit` command.

**Comment by randy3k** [comment]
could you open python/or the sublime console and run
```
import subprocess; subprocess.check_output(['sh', '-c', 'ulimit -Sn'])
```

**Comment by poroale** [comment]
I ran the command in Sublime console and got the following:
```
>>> import subprocess; subprocess.check_output(['sh', '-c', 'ulimit -Sn'])
b'1024\n'
```
In regular bash `ulimit` works fine.

**Comment by randy3k** [comment]
Thanks. I have updated the dependencies `ptyprocess`. Please do the following

1. uninstall Console
2. make sure the folder `ptyprocess` is removed under the folder of `Preferences: Browse Packages`
3. restart Sublime Text and reinstall Console

**Comment by poroale** [comment]
Thank you, that did the trick!

**Comment by ThirtyThreeB** [comment]
@randy3k I'm having this same problem.  What do you mean 'uninstall Console'?  I don't see that as an option in ST3

**Comment by randy3k** [comment]
Terminus was called "Console". Just try reinstalling Terminus
